from . import sale_order
from . import product_category
from . import product_pricelist
from . import product_product
from . import product_template
from . import res_company
from . import res_partner
from . import res_user
from . import portal
