from . import stock_picking
from . import delivery_carrier
from . import stock_move
from . import product
from . import stock_warehouse
from . import stock_orderpoint
from . import sale_order_line
from . import ir_actions_report
from . import stock_location
from . import stock_quant
from . import stock_location_route
from . import stock_rule
from . import stock_move_line
from . import stock_inventory
